### ISSUE TITLE
Cirrus CI tests are super expensive due to image building

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#771]
Here is our Cirrus CI configuration

```
task:
  timeout_in: 120m
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-0-snap

  env:
    ASSUME_ALWAYS_YES: YES
  setup_script:
    - pkg update -f
    - pkg install bash
    - pkg install cmake
    - pkg install git
  build_script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j
  test_script:
    - cd build
    - ctest  -j4 --output-on-failure -E checkperf
```

99% of the time is spent doing the "pkg install" work.

@eddelbuettel  can you help? How do I make this go faster? I understand that freebsd-13-0-snap is a Google Cloud image.
